on:
  push:
    branches: [ master ]
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      amd64: 64-bit
      386: 32-bit
      arm64: ARM_64-bit
      arm: ARM_32-bit
      linux: Linux
      darwin: Darwin

    
        

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          workdir: go/
          version: latest
          args: release --rm-dist
