on:
  push:
    branches: [ master ]
    
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt install golang unzip
      - name: Print Versions
        run: |
           go version
      - name: Install aws-cl
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: where am i?
        run: |
          pwd
          ls
      - name: Run Make release
        run: |
          cd go
          make all
          make release
      - name: See dist bin directory
        run: ls -la bin
